// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package book_api

type Author struct {
	Name string `json:"name"`
}

type Book struct {
	Isbn   string  `json:"isbn"`
	Name   string  `json:"name"`
	Author *Author `json:"author"`
}

type NewBook struct {
	Isbn       string `json:"isbn"`
	Name       string `json:"name"`
	Authorname string `json:"authorname"`
}

type UpdateBook struct {
	Isbn       string  `json:"isbn"`
	Name       *string `json:"name"`
	Authorname *string `json:"authorname"`
}
